import { GET_CONTACT_LIST } from "@/graphql/queries";
import { useQuery } from "@apollo/client";
import { css } from "@emotion/react";
import Head from "next/head";

const styles = {
  main: css({
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    gap: "1.25rem",
    padding: "6rem",
    minHeight: "100vh",
  }),
};

export default function Home() {
  const { data } = useQuery(GET_CONTACT_LIST, {
    variables: {
      limit: 1,
    },
  });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main css={styles.main}></main>
    </>
  );
}
